# Playbook for Ansible Windows workshop setup.
---
- name: Provision Instances
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - vars/main.yml
  tags:
    - manage-instances
  tasks:
  - include_role:
      name: "manage-{{ instance_loc }}-instances"

# Configure Active Directory
- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers
  gather_facts: no
  vars_files:
    - vars/main.yml
  tags:
    - windows-ad-controller
  roles:
    - windows-ad-controller

# Configure Workstation host
- name: Configure Windows Workstation
  hosts: windows_workstations
  vars_files:
    - vars/main.yml
  gather_facts: True
  tags:
    - windows-workstation
  roles:
    - windows-common
    - windows-workstation

# Configure Tower host
- name: Configure Ansible Host
  hosts: tower
  become: True
  #remote_user: "{{ root_user }}"
  gather_facts: false
  vars_files:
    - vars/main.yml
  tags:
    - ansible-tower
  roles:
    - linux-common
    - ansible-tower

# Configure Windows Hosts
- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - windows_hosts
  roles:
    - windows-common

# Configure GitLab Host
- name: Configure GitLab Host
  hosts: gitlab
  become: True
  remote_user: "{{ root_user }}"
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - gitlab
  roles:
    - { role: linux-common }
    - { role: geerlingguy.gitlab }

# Run post-config separate to avoid handler restart issue...
- name: Gitlab Post Config
  hosts: gitlab
  become: True
  remote_user: "{{ root_user }}"
  gather_facts: True
  vars_files:
    - vars/main.yml
  tags:
    - gitlab
  roles:
    - { role: gitlab-postconfig }
