- name: Destroy lab instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/main.yml

  tasks:
  - include_role:
      name: "teardown-{{ instance_loc }}-instances"

  post_tasks:
    - name: Remove inventory files
      file: path="{{ item }}" state=absent
      with_fileglob: "{{ playbook_dir }}/*.txt"
      register: removal
      changed_when: removal|success
