---
- name: Remove PeerDNS=yes entry
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens192
    regexp: '^PEERDNS=yes'
    line: ''

- name: set DNS resolution in ifcfg file
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-ens192
    block: |
      DNS1={{ dns_server }}
      DNS2=8.8.8.8
      DOMAIN="{{dns_domain_name}} ec2.internal"
      PEERDNS=no
  register: nm_resolv
  ignore_errors: true

- name: restart NetworkManager service
  service:
    name: NetworkManager
    state: restarted
  when: nm_resolv.changed

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - bind-utils
